site_name: CC Docs
site_description: Crystal Clear Documentation 
nav:
    - Home: 'index.md'
    - FAQ: 'FAQ.md'
    - 'Main Documentation':
        - 'Documentation': 'Documentation.md'
        - 'Items': 'Items.md'
        - 'Music': 'Music.md'
    - 'Changelogs':
        - 'v2.1.0': 'changelogs/2_1_0_Changelog.md'
        - 'Previous Changelogs': 'Changelogs.md'
        - 'Credits': 'Credits.md'
